name: CI/CD Pipeline

on:
    push:
        branches:
            - main  # Adjust this if you use a different branch for releases

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '18'  # Use your project's Node.js version
            - name: Install dependencies
              run: npm install
            - name: Run tests
              run: npm test

    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '18'  # Use your project's Node.js version
            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm run build  # Adjust if you have a different build script

    semantic-release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0  # Fetch all history for all branches and tags
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '18'  # Use your project's Node.js version
                  registry-url: 'https://registry.npmjs.org'
            - name: Install dependencies
              run: npm ci
            - name: Semantic Release
              run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
